---
- hosts: all
  gather_facts: no
  tasks:
    - name: Start all the instaces
      ec2:
        region: us-east-1 
        instance_tags: 
          Testing: Hello
        state: running
        wait: yes
