---
- hosts: all
  tasks:
    - name: get all ec2 data
      ec2_instance_facts:
        region: us-east-1
        filters:
          "tag:Testing": Hello
      register: instance_facts
      
    - name: Start all the instaces
      ec2:
        instance_ids: "{{ item.instance_id }}"
        state: running
        wait: yes
      with_items: instance_facts.instances
