---
- hosts: all
  tasks:
    - name: get all ec2 data
      ec2_instance_facts:
        region: us-east-1
        filters:
          "tag:Testing": Hello
      register: instance_facts
      
    - name: get all instance id
      set_fact:
        ec2_instances: |
          {% set instances = [] %}
          {% for item in instance_facts.instances -%}
            {{ instances.append(item.id) }}
          {%- endfor %}
          {{ instances }}
      
    - name: Debug
      debug:
        var: instances
        
    - name: Start all the instaces
      ec2:
        region: us-east-1 
        instance_ids: "{{ item }}"
        state: stopped
        wait: yes
      with_items: "{{ ec2_instances }}"
