- name: Windows Patching
  hosts: all
  tasks:
    - name: Wait for system to become reachable over WinRM
      wait_for_connection:
        timeout: 900 

    - name: Create logs director
      win_file:
        path: c:\slmtools\logs
        state: directory

    - name: Create scripts directory
      win_file:
        path: c:\slmtools\scripts
        state: directory

    - name: Copy Pending Reboot Script to local machine
      win_copy:
        src: Get-pendingReboot.ps1
        dest: c:\slmtools\scripts\Get-pendingReboot.ps1

    - name: Copy Powershell Script to local machines
      win_copy:
        src: windows-updateps.ps1
        dest: c:\slmtools\scripts\windows-updateps.ps1		

    - name: Check for pending reboots
      raw: . c:\slmtools\scripts\Get-pendingReboot.ps1; Get-pendingReboot | ConvertTo-Json
      register: pending_reboot_result

    - name: Reboot target host if necessary
      win_command: shutdown /r /f /t 60
      args:
        chdir: c:\
      register: wr_result
      when: (pending_reboot_result.stdout | from_json).RebootPending == true

# Begin WSUS cleanup (see comment above)
    - name: Stop the Windows Update service
      win_service:
        name: wuauserv
        state: stopped
        start_mode: disabled

    - name: Remove potentially invalid WSUS information from file system
      win_file:
        state: absent
        path: C:\Windows\SoftwareDistribution

    - name: Remove potentially invalid WSUS information from registry (WUServer)
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
        name: WUServer
        state: absent

    - name: Remove potentially invalid WSUS information from registry (WUStatusServer)
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
        name: WUStatusServer
        state: absent

    - name: Start the Windows Update service
      win_service:
        name: wuauserv
        state: started
        start_mode: auto
# End WSUS cleanup (see comment above)

    - name: Run windows update on target host
      win_shell: ./windows-updateps.ps1 
      args: 
        chdir: c:\slmtools\scripts\ 
      register: wu_result   

    - name: Show results
      debug:
        msg: "{{wu_result}}"

    - name: Wait for system to become reachable over WinRM
      wait_for_connection:
        timeout: 90000  
