 - name: Wait for system to become reachable over WinRM
   wait_for_connection:
   timeout: 90000
- name: Create logs director
  win_file:
    path: c:\slmtools\logs
    state: directory

- name: Create scripts directory
  win_file:
    path: c:\slmtools\scripts
    state: directory
- name: Copy Pending Reboot Script to local machine
  win_copy:
    src: Get-pendingReboot.ps1
    dest: c:\slmtools\scripts\Get-pendingReboot.ps1

- name: Copy Powershell Script to local machines
  win_copy:
    src: windows-updateps.ps1
    dest: c:\slmtools\scripts\windows-updateps.ps1		
- name: Check for pending reboots
  raw: . c:\slmtools\scripts\Get-pendingReboot.ps1; Get-pendingReboot | ConvertTo-Json
  register: pending_reboot_result
- name: Reboot target host if necessary
  win_command: shutdown /r /f /t 60
  args:
    chdir: c:\
    register: wr_result
  when: (pending_reboot_result.stdout | from_json).RebootPending == true
