- name: Stop the Windows Update service
  win_service:
    name: wuauserv
    state: stopped
    start_mode: disabled

- name: Remove potentially invalid WSUS information from file system
  win_file:
    state: absent
    path: C:\Windows\SoftwareDistribution

- name: Remove potentially invalid WSUS information from registry (WUServer)
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: WUServer
    state: absent

- name: Remove potentially invalid WSUS information from registry (WUStatusServer)
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: WUStatusServer
    state: absent

- name: Start the Windows Update service
  win_service:
    name: wuauserv
    state: started
    start_mode: auto

- name: Copy Powershell Script to local machines
  win_copy:
    src: security.ps
    dest: c:\slmtools\scripts\security.ps1

- name: Run windows update on target host
  win_shell: ./security.ps1 
  args: 
    chdir: c:\slmtools\scripts\ 
  register: wu_result   

- name: Show results
  debug:
    msg: "{{wu_result}}"
